#define MODEL_Root              0x2B
#define MODEL_MeshModel         0x2A
#define MODEL_Stage             0x29
#define MODEL_WellSnowTop       0x28
#define MODEL_Well              0x27
#define MODEL_Rock              0x26
#define MODEL_Weeds             0x25
#define MODEL_Bush              0x24
#define MODEL_Bushes            0x23
#define MODEL_TreeStumpTop      0x22
#define MODEL_TreeStump         0x21
#define MODEL_Tree2             0x20
#define MODEL_Tree1             0x1F
#define MODEL_HedgeBlock        0x1E
#define MODEL_Hedges            0x1D
#define MODEL_WallBrick         0x1C
#define MODEL_WallTrim          0x1B
#define MODEL_WallBlocks        0x1A
#define MODEL_WallSnowTop       0x19
#define MODEL_WallTopSpike      0x18
#define MODEL_CellarStairs      0x17
#define MODEL_CellarEntrance    0x16
#define MODEL_CellarDoor        0x15
#define MODEL_FloorPathSnow     0x14
#define MODEL_FloorSnow         0x13
#define MODEL_MansionTrim       0x12
#define MODEL_Stairs2           0x11
#define MODEL_Stairs1           0x10
#define MODEL_DoorBoards        0xF
#define MODEL_Door              0xE
#define MODEL_Windows           0xD
#define MODEL_Fence             0xC
#define MODEL_MansionBlock      0xB
#define MODEL_MansionBricks     0xA
#define MODEL_MansionWood       0x9
#define MODEL_MansionPillars    0x8
#define MODEL_MansionPatioFloor 0x7
#define MODEL_MansionPatioWall  0x6
#define MODEL_MansionPatioRoof  0x5
#define MODEL_MansionWindowSpace 0x4
#define MODEL_MansionRoof       0x3
#define MODEL_MansionRoofSpikes 0x2
#define MODEL_FountainShine     0x1
#define MODEL_Fountain          0x0

