#message:26:(ItemName_FireFlower) {
	Fire Flower[End]
}

#message:26:(ItemName_SnowmanDoll) {
	Snowman Doll[End]
}

#message:26:(ItemName_ThunderRage) {
	Thunder Rage[End]
}

#message:26:(ItemName_ThunderBolt) {
	Thunder Bolt[End]
}

#message:26:(ItemName_ShootingStar) {
	Shooting Star[End]
}

#message:26:(ItemName_DustyHammer) {
	Dusty Hammer[End]
}

#message:26:(ItemName_Pebble) {
	Pebble[End]
}

#message:26:(ItemName_StoneCap) {
	Stone Cap[End]
}

#message:26:(ItemName_VoltShroom) {
	Volt Shroom[End]
}

#message:26:(ItemName_Mushroom) {
	Mushroom[End]
}

#message:26:(ItemName_SuperShroom) {
	Super Shroom[End]
}

#message:26:(ItemName_UltraShroom) {
	Ultra Shroom[End]
}

#message:26:(ItemName_LifeShroom) {
	Life Shroom[End]
}

#message:26:(ItemName_DriedShroom) {
	Dried Shroom[End]
}

#message:26:(ItemName_TastyTonic) {
	Tasty Tonic[End]
}

#message:26:(ItemName_SuperSoda) {
	Super Soda[End]
}

#message:26:(ItemName_BlueBerry) {
	Blue Berry[End]
}

#message:26:(ItemName_RedBerry) {
	Red Berry[End]
}

#message:26:(ItemName_YellowBerry) {
	Yellow Berry[End]
}

#message:26:(ItemName_BubbleBerry) {
	Bubble Berry[End]
}

#message:26:(ItemName_Lime) {
	Lime[End]
}

#message:26:(ItemName_Lemon) {
	Lemon[End]
}

#message:26:(ItemName_HoneySyrup) {
	Honey Syrup[End]
}

#message:26:(ItemName_MapleSyrup) {
	Maple Syrup[End]
}

#message:26:(ItemName_JamminJelly) {
	Jammin' Jelly[End]
}

#message:26:(ItemName_WhackasBump) {
	Whacka's Bump[End]
}

#message:26:(ItemName_Apple) {
	Apple[End]
}

#message:26:(ItemName_Goomnut) {
	Goomnut[End]
}

#message:26:(ItemName_KoopaLeaf) {
	Koopa Leaf[End]
}

#message:26:(ItemName_DriedPasta) {
	Dried Pasta[End]
}

#message:26:(ItemName_DriedFruit) {
	Dried Fruit[End]
}

#message:26:(ItemName_StrangeLeaf) {
	Strange Leaf[End]
}

#message:26:(ItemName_CakeMix) {
	Cake Mix[End]
}

#message:26:(ItemName_Egg) {
	Egg[End]
}

#message:26:(ItemName_Coconut) {
	Coconut[End]
}

#message:26:(ItemName_Melon) {
	Melon[End]
}

#message:26:(ItemName_StinkyHerb) {
	Stinky Herb[End]
}

#message:26:(ItemName_IcedPotato) {
	Iced Potato[End]
}

#message:26:(ItemName_SleepySheep) {
	Sleepy Sheep[End]
}

#message:26:(ItemName_POWBlock) {
	POW Block[End]
}

#message:26:(ItemName_StopWatch) {
	Stop Watch[End]
}

#message:26:(ItemName_DizzyDial) {
	Dizzy Dial[End]
}

#message:26:(ItemName_FrightJar) {
	Fright Jar[End]
}

#message:26:(ItemName_Mystery) {
	Mystery?[End]
}

#message:26:(ItemName_RepelGel) {
	Repel Gel[End]
}

#message:26:(ItemName_SpicySoup) {
	Spicy Soup[End]
}

#message:26:(ItemName_ApplePie) {
	Apple Pie[End]
}

#message:26:(ItemName_HoneyShroom) {
	Honey Shroom[End]
}

#message:26:(ItemName_MapleShroom) {
	Maple Shroom[End]
}

#message:26:(ItemName_JellyShroom) {
	Jelly Shroom[End]
}

#message:26:(ItemName_HoneySuper) {
	Honey Super[End]
}

#message:26:(ItemName_MapleSuper) {
	Maple Super[End]
}

#message:26:(ItemName_JellySuper) {
	Jelly Super[End]
}

#message:26:(ItemName_HoneyUltra) {
	Honey Ultra[End]
}

#message:26:(ItemName_MapleUltra) {
	Maple Ultra[End]
}

#message:26:(ItemName_JellyUltra) {
	Jelly Ultra[End]
}

#message:26:(ItemName_Koopasta) {
	Koopasta[End]
}

#message:26:(ItemName_FriedShroom) {
	Fried Shroom[End]
}

#message:26:(ItemName_HotShroom) {
	Hot Shroom[End]
}

#message:26:(ItemName_ShroomSteak) {
	Shroom Steak[End]
}

#message:26:(ItemName_ShroomCake) {
	Shroom Cake[End]
}

#message:26:(ItemName_SweetShroom) {
	Sweet Shroom[End]
}

#message:26:(ItemName_BlandMeal) {
	Bland Meal[End]
}

#message:26:(ItemName_YummyMeal) {
	Yummy Meal[End]
}

#message:26:(ItemName_DeluxeFeast) {
	Deluxe Feast[End]
}

#message:26:(ItemName_SpecialShake) {
	Special Shake[End]
}

#message:26:(ItemName_HealthyJuice) {
	Healthy Juice[End]
}

#message:26:(ItemName_BigCookie) {
	Big Cookie[End]
}

#message:26:(ItemName_Cake) {
	Cake[End]
}

#message:26:(ItemName_Mistake) {
	Mistake[End]
}

#message:26:(ItemName_KoopaTea) {
	Koopa Tea[End]
}

#message:26:(ItemName_Spaghetti) {
	Spaghetti[End]
}

#message:26:(ItemName_EggMissile) {
	Egg Missile[End]
}

#message:26:(ItemName_FriedEgg) {
	Fried Egg[End]
}

#message:26:(ItemName_HoneyCandy) {
	Honey Candy[End]
}

#message:26:(ItemName_ElectroPop) {
	Electro Pop[End]
}

#message:26:(ItemName_FirePop) {
	Fire Pop[End]
}

#message:26:(ItemName_LimeCandy) {
	Lime Candy[End]
}

#message:26:(ItemName_CocoPop) {
	Coco Pop[End]
}

#message:26:(ItemName_LemonCandy) {
	Lemon Candy[End]
}

#message:26:(ItemName_JellyPop) {
	Jelly Pop[End]
}

#message:26:(ItemName_StrangeCake) {
	Strange Cake[End]
}

#message:26:(ItemName_KookyCookie) {
	Kooky Cookie[End]
}

#message:26:(ItemName_FrozenFries) {
	Frozen Fries[End]
}

#message:26:(ItemName_PotatoSalad) {
	Potato Salad[End]
}

#message:26:(ItemName_NuttyCake) {
	Nutty Cake[End]
}

#message:26:(ItemName_BoiledEgg) {
	Boiled Egg[End]
}

#message:26:(ItemName_YoshiCookie) {
	Yoshi Cookie[End]
}

#message:26:(ItemName_PowerJump) {
	Power Jump[End]
}

#message:26:(ItemName_MegaJump) {
	Mega Jump[End]
}

#message:26:(ItemName_JumpCharge) {
	Jump Charge[End]
}

#message:26:(ItemName_SJumpChg) {
	S. Jump Chg.[End]
}

#message:26:(ItemName_SleepStomp) {
	Sleep Stomp[End]
}

#message:26:(ItemName_DizzyStomp) {
	Dizzy Stomp[End]
}

#message:26:(ItemName_Multibounce) {
	Multibounce[End]
}

#message:26:(ItemName_ShrinkStomp) {
	Shrink Stomp[End]
}

#message:26:(ItemName_DDownJump) {
	D-Down Jump[End]
}

#message:26:(ItemName_PowerBounce) {
	Power Bounce[End]
}

#message:26:(ItemName_PowerSmash) {
	Power Smash[End]
}

#message:26:(ItemName_MegaSmash) {
	Mega Smash[End]
}

#message:26:(ItemName_SmashCharge) {
	Smash Charge[End]
}

#message:26:(ItemName_SSmashChg) {
	S. Smash Chg.[End]
}

#message:26:(ItemName_HammerThrow) {
	Hammer Throw[End]
}

#message:26:(ItemName_ShrinkSmash) {
	Shrink Smash[End]
}

#message:26:(ItemName_SpinSmash) {
	Spin Smash[End]
}

#message:26:(ItemName_DDownPound) {
	D-Down Pound[End]
}

#message:26:(ItemName_QuakeHammer) {
	Quake Hammer[End]
}

#message:26:(ItemName_PowerQuake) {
	Power Quake[End]
}

#message:26:(ItemName_MegaQuake) {
	Mega Quake[End]
}

#message:26:(ItemName_DoubleDip) {
	Double Dip[End]
}

#message:26:(ItemName_TripleDip) {
	Triple Dip[End]
}

#message:26:(ItemName_GroupFocus) {
	Group Focus[End]
}

#message:26:(ItemName_QuickChange) {
	Quick Change[End]
}

#message:26:(ItemName_HPPlus) {
	HP Plus[End]
}

#message:26:(ItemName_FPPlus) {
	FP Plus[End]
}

#message:26:(ItemName_PowerPlus) {
	Power Plus[End]
}

#message:26:(ItemName_DefendPlus) {
	Defend Plus[End]
}

#message:26:(ItemName_DamageDodge) {
	Damage Dodge[End]
}

#message:26:(ItemName_PUpDDown) {
	P-Up, D-Down[End]
}

#message:26:(ItemName_PDownDUp) {
	P-Down, D-Up[End]
}

#message:26:(ItemName_HPDrain) {
	HP Drain[End]
}

#message:26:(ItemName_HappyHeart) {
	Happy Heart[End]
}

#message:26:(ItemName_HappyFlower) {
	Happy Flower[End]
}

#message:26:(ItemName_FlowerSaver) {
	Flower Saver[End]
}

#message:26:(ItemName_HeartFinder) {
	Heart Finder[End]
}

#message:26:(ItemName_FlowerFinder) {
	Flower Finder[End]
}

#message:26:(ItemName_DeepFocus) {
	Deep Focus[End]
}

#message:26:(ItemName_SpikeShield) {
	Spike Shield[End]
}

#message:26:(ItemName_DodgeMaster) {
	Dodge Master[End]
}

#message:26:(ItemName_PrettyLucky) {
	Pretty Lucky[End]
}

#message:26:(ItemName_LuckyDay) {
	Lucky Day[End]
}

#message:26:(ItemName_CloseCall) {
	Close Call[End]
}

#message:26:(ItemName_PowerRush) {
	Power Rush[End]
}

#message:26:(ItemName_LastStand) {
	Last Stand[End]
}

#message:26:(ItemName_MegaRush) {
	Mega Rush[End]
}

#message:26:(ItemName_FirstAttack) {
	First Attack[End]
}

#message:26:(ItemName_BumpAttack) {
	Bump Attack[End]
}

#message:26:(ItemName_SpinAttack) {
	Spin Attack[End]
}

#message:26:(ItemName_DizzyAttack) {
	Dizzy Attack[End]
}

#message:26:(ItemName_SpeedySpin) {
	Speedy Spin[End]
}

#message:26:(ItemName_FeelingFine) {
	Feeling Fine[End]
}

#message:26:(ItemName_AttackFXA) {
	Attack FX A[End]
}

#message:26:(ItemName_AttackFXD) {
	Attack FX D[End]
}

#message:26:(ItemName_AttackFXB) {
	Attack FX B[End]
}

#message:26:(ItemName_AttackFXE) {
	Attack FX E[End]
}

#message:26:(ItemName_AttackFXC) {
	Attack FX C[End]
}

#message:26:(ItemName_AttackFXF) {
	Attack FX F[End]
}

#message:26:(ItemName_AllorNothing) {
	All or Nothing[End]
}

#message:26:(ItemName_SlowGo) {
	Slow Go[End]
}

#message:26:(ItemName_IcePower) {
	Ice Power[End]
}

#message:26:(ItemName_PayOff) {
	Pay-Off[End]
}

#message:26:(ItemName_FireShield) {
	Fire Shield[End]
}

#message:26:(ItemName_ChillOut) {
	Chill Out[End]
}

#message:26:(ItemName_ZapTap) {
	Zap Tap[End]
}

#message:26:(ItemName_MoneyMoney) {
	Money Money[End]
}

#message:26:(ItemName_RightOn) {
	Right On![End]
}

#message:26:(ItemName_RunawayPay) {
	Runaway Pay[End]
}

#message:26:(ItemName_Refund) {
	Refund[End]
}

#message:26:(ItemName_ISpy) {
	I Spy[End]
}

#message:26:(ItemName_Peekaboo) {
	Peekaboo[End]
}

#message:26:(ItemName_Boots) {
	Jump[End]
}

#message:26:(ItemName_SuperBoots) {
	Spin Jump[End]
}

#message:26:(ItemName_UltraBoots) {
	Tornado Jump[End]
}

#message:26:(ItemName_Hammer) {
	Hammer[End]
}

#message:26:(ItemName_SuperHammer) {
	Super Hammer[End]
}

#message:26:(ItemName_UltraHammer) {
	Ultra Hammer[End]
}

#message:26:(ItemName_LuckyStar) {
	Lucky Star[End]
}

#message:26:(ItemName_KoopaFortressKey) {
	Fortress Key[End]
}

#message:26:(ItemName_RuinsKey) {
	Ruins Key[End]
}

#message:26:(ItemName_TubbaCastleKey) {
	Castle Key[End]
}

#message:26:(ItemName_CrystalPalaceKey) {
	Palace Key[End]
}

#message:26:(ItemName_BowserCastleKey) {
	Castle Key[End]
}

#message:26:(ItemName_PeachKey) {
	Castle Key[End]
}

#message:26:(ItemName_OddKey) {
	Odd Key[End]
}

#message:26:(ItemName_Dolly) {
	Dolly[End]
}

#message:26:(ItemName_KooperShell) {
	Kooper's Shell[End]
}

#message:26:(ItemName_PulseStone) {
	Pulse Stone[End]
}

#message:26:(ItemName_Artifact) {
	Artifact[End]
}

#message:26:(ItemName_GoldenJar) {
	Golden Jar[End]
}

#message:26:(ItemName_LunarStone) {
	Lunar Stone[End]
}

#message:26:(ItemName_PyramidStone) {
	Pyramid Stone[End]
}

#message:26:(ItemName_DiamondStone) {
	Diamond Stone[End]
}

#message:26:(ItemName_BooRecord) {
	Record[End]
}

#message:26:(ItemName_BooWeight) {
	Weight[End]
}

#message:26:(ItemName_BooPortrait) {
	Boo's Portrait[End]
}

#message:26:(ItemName_MysticalKey) {
	Mystical Key[End]
}

#message:26:(ItemName_StoreroomKey) {
	Storeroom Key[End]
}

#message:26:(ItemName_ToyTrain) {
	Toy Train[End]
}

#message:26:(ItemName_FryingPan) {
	Frying Pan[End]
}

#message:26:(ItemName_Dictionary) {
	Dictionary[End]
}

#message:26:(ItemName_MysteryNote) {
	Mystery Note[End]
}

#message:26:(ItemName_Mailbag) {
	Mailbag[End]
}

#message:26:(ItemName_MagicalSeed1) {
	Magical Seed[End]
}

#message:26:(ItemName_MagicalSeed2) {
	Magical Seed[End]
}

#message:26:(ItemName_MagicalSeed3) {
	Magical Seed[End]
}

#message:26:(ItemName_MagicalSeed4) {
	Magical Seed[End]
}

#message:26:(ItemName_CrystalBerry) {
	Crystal Berry[End]
}

#message:26:(ItemName_WaterStone) {
	Water Stone[End]
}

#message:26:(ItemName_MagicalBean) {
	Magical Bean[End]
}

#message:26:(ItemName_FertileSoil) {
	Fertile Soil[End]
}

#message:26:(ItemName_MiracleWater) {
	Miracle Water[End]
}

#message:26:(ItemName_CrystalBall) {
	Crystal Ball[End]
}

#message:26:(ItemName_Calculator) {
	Calculator[End]
}

#message:26:(ItemName_Cookbook) {
	Cookbook[End]
}

#message:26:(ItemName_JadeRaven) {
	Jade Raven[End]
}

#message:26:(ItemName_VolcanoVase) {
	Volcano Vase[End]
}

#message:26:(ItemName_WarehouseKey) {
	Warehouse Key[End]
}

#message:26:(ItemName_SnowmanBucket) {
	Bucket[End]
}

#message:26:(ItemName_SnowmanScarf) {
	Scarf[End]
}

#message:26:(ItemName_StarStone) {
	Star Stone[End]
}

#message:26:(ItemName_RedKey) {
	Red Key[End]
}

#message:26:(ItemName_BlueKey) {
	Blue Key[End]
}

#message:26:(ItemName_SneakyParasol) {
	Sneaky Parasol[End]
}

#message:26:(ItemName_PrisonKey) {
	Prison Key[End]
}

#message:26:(ItemName_Lyrics) {
	Lyrics[End]
}

#message:26:(ItemName_Melody) {
	Melody[End]
}

#message:26:(ItemName_BakingSugar) {
	Sugar[End]
}

#message:26:(ItemName_BakingSalt) {
	Salt[End]
}

#message:26:(ItemName_BakingEgg) {
	Egg[End]
}

#message:26:(ItemName_BakingCream) {
	Cream[End]
}

#message:26:(ItemName_BakingStrawberry) {
	Strawberry[End]
}

#message:26:(ItemName_BakingButter) {
	Butter[End]
}

#message:26:(ItemName_BakingCleanser) {
	Cleanser[End]
}

#message:26:(ItemName_BakingWater) {
	Water[End]
}

#message:26:(ItemName_BakingFlour) {
	Flour[End]
}

#message:26:(ItemName_BakingMilk) {
	Milk[End]
}

#message:26:(ItemName_FirstDegreeCard) {
	First-Degree Card[End]
}

#message:26:(ItemName_SecondDegreeCard) {
	Second-Degree Card[End]
}

#message:26:(ItemName_ThirdDegreeCard) {
	Third-Degree Card[End]
}

#message:26:(ItemName_FourthDegreeCard) {
	Fourth-Degree Card[End]
}

#message:26:(ItemName_Diploma) {
	Diploma[End]
}

#message:26:(ItemName_UltraStone) {
	Ultra Stone[End]
}

#message:26:(ItemName_SilverCredit) {
	Silver Credit[End]
}

#message:26:(ItemName_GoldCredit) {
	Gold Credit[End]
}

#message:26:(ItemName_Letter25) {
	Letter[End]
}

#message:26:(ItemName_Letter01) {
	Letter[End]
}

#message:26:(ItemName_Letter02) {
	Letter[End]
}

#message:26:(ItemName_Letter03) {
	Letter[End]
}

#message:26:(ItemName_Letter04) {
	Letter[End]
}

#message:26:(ItemName_Letter05) {
	Letter[End]
}

#message:26:(ItemName_Letter06) {
	Letter[End]
}

#message:26:(ItemName_Letter07) {
	Letter[End]
}

#message:26:(ItemName_Letter08) {
	Letter[End]
}

#message:26:(ItemName_Letter09) {
	Letter[End]
}

#message:26:(ItemName_Letter10) {
	Letter[End]
}

#message:26:(ItemName_Letter11) {
	Letter[End]
}

#message:26:(ItemName_Letter12) {
	Letter[End]
}

#message:26:(ItemName_Letter13) {
	Letter[End]
}

#message:26:(ItemName_Letter14) {
	Letter[End]
}

#message:26:(ItemName_Letter15) {
	Letter[End]
}

#message:26:(ItemName_Letter16) {
	Letter[End]
}

#message:26:(ItemName_Letter17) {
	Letter[End]
}

#message:26:(ItemName_Letter18) {
	Letter[End]
}

#message:26:(ItemName_Letter19) {
	Letter[End]
}

#message:26:(ItemName_Letter20) {
	Letter[End]
}

#message:26:(ItemName_Letter21) {
	Letter[End]
}

#message:26:(ItemName_Letter22) {
	Letter[End]
}

#message:26:(ItemName_Letter23) {
	Letter[End]
}

#message:26:(ItemName_Letter24) {
	Letter[End]
}

#message:26:(ItemName_KootKoopaLegends) {
	Koopa Legends[End]
}

#message:26:(ItemName_KootTheTape) {
	Tape[End]
}

#message:26:(ItemName_KootLuigiAutograph) {
	Autograph[End]
}

#message:26:(ItemName_KootEmptyWallet) {
	Empty Wallet[End]
}

#message:26:(ItemName_KootMerluvleeAutograph) {
	Autograph[End]
}

#message:26:(ItemName_KootOldPhoto) {
	Old Photo[End]
}

#message:26:(ItemName_KootGlasses) {
	Glasses[End]
}

#message:26:(ItemName_KootPackage) {
	Package[End]
}

#message:26:(ItemName_KootRedJar) {
	Red Jar[End]
}

#message:26:(ItemName_StarPiece) {
	Star Piece[End]
}
