#message:2F:(FotB_0000)
{
[Style right]
Hmm..[BR]
The forest feels different from[BR]
when I left this morning...[BR]
[Wait][End]
}







#message:2F:(FotB_0001)
{
[Style right]
Let's be careful![BR]
[Wait][End]
}







#message:2F:(FotB_0002)
{
[Style right]
Getting lost in this weather[BR]
is a death sentence![BR]
[Wait][End]
}







#message:2F:(FotB_0003)
{
[Style Inspect]
The gate won't move, it's jammed.[BR]
[Wait][End]
}







#message:2F:(FotB_0004)
{
[Style Inspect]
There are noises coming from[BR]
the rock.[BR]
[Wait][Next]
It sounds like snickering.[BR]
[Wait][End]
}






#message:2F:(FotB_0005)
{
[Style right]
This doesn't seem right..[BR]
[Wait][Next]
We shouldn't be in this part[BR]
of the forest, did we wander[BR]
off the path?[BR]
[Wait][End]
}






#message:2F:(FotB_0006)
{
[Style right]
Let's keep going, Bootler will be[BR]
worried if we dawdle too long.[BR]
[Wait][End]
}






#message:2F:(FotB_0007)
{
[Style right]
Oh look, it's that forest guide![BR]
[Wait][Next]
Hey, you![BR]
[Wait][End]
}






#message:2F:(FotB_0008)
{
[Style right]
Maybe he's hard of hearing,[BR]
let's try this...[BR]
[Wait][End]
}






#message:2F:(FotB_0009)
{
[InputOff]
[Style right]
[Down 10][Shake][PrintRising][Size 32,32]Gwaah ha ha ha![BR]
[Pause 25][End]
}






#message:2F:(FotB_000A)
{
[Style right]
Hey! Don't just ignore us like[BR]
that you lout! Come back here![BR]
[Wait][End]
}






#message:2F:(FotB_000B)
{
[Style right]
Maybe he's heading for an exit?[BR]
Let's follow him![BR]
[Wait][End]
}






#message:2F:(FotB_000C)
{
[Style right]
There he is![BR]
[Wait][End]
}






#message:2F:(FotB_000D)
{
[Style right]
Hey Okey! ...Dokey? No, no..[BR]
[Wait][End]
}






#message:2F:(FotB_000E)
{
[Style right]
...Oaklie! That's it! Hey Oaklie![BR]
We request your help![BR]
[Wait][End]
}






#message:2F:(FotB_000F)
{
[Style right]
This forest has us all turned[BR]
around! There's blocked routes[BR]
and irregular paths everywhere![BR]
[Wait][Next]
What's going on? Can you help us?[BR]
[Wait][End]
}






#message:2F:(FotB_0010)
{
[Style right]
....or just send us in the right...[BR]
direction?[BR]
[Wait][End]
}






#message:2F:(FotB_0011)
{
[Style right]
AHHH! Mario, they tricked us,[BR]
it was a trap![BR]
[Wait][End]
}






#message:2F:(FotB_0012)
{
[Style right]
More like an am-[Shake]BOO
[Shake]Heh heh heh!
[Wait][End]
}






#message:2F:(FotB_0013)
{
[Style right]
Bleh! This wasn't fun at all![BR]
[Wait][Next]
I'm not missing the party for[BR]this, I was lookout last time!![BR]
[Wait][End]
}






#message:2F:(FotB_0014)
{
[Style right]
See ya twerps! Have fun[BR]
getting lost in the forest again![BR]
[Wait][End]
}






#message:2F:(FotB_0015)
{
[Style right]
Party? What on earth were[BR]
they talking about?[BR]
[Wait][End]
}






#message:2F:(FotB_0016)
{
[Style right]
...OUR party!? They better not[BR]
think they have a dinner invitation[BR]
after that mess![BR]
[Wait][Next]
Who on earth invited them?[BR]
I will not have ill-mannered[BR]
bullies at my home![BR]
[Wait][End]
}






#message:2F:(FotB_0017)
{
[Style right]
[Wave]Oooo.... ughhh.....
[Wait][End]
}






#message:2F:(FotB_0018)
{
[Style right]
You think you can scare us[BR]
after running away? You lot give[BR]
Boos a bad name![BR]
[Wait][End]
}






#message:2F:(FotB_0019)
{
[Style right]
...Oh? From the chest?[BR]
[Wait][End]
}






#message:2F:(FotB_001A)
{
[Style right]
My mistake, let's get him[BR]
out of there.[BR]
[Wait][End]
}






#message:2F:(FotB_001B)
{
[Style right]
Oof... What a bunch of rude kids...[BR]
[Wait][End]
}






#message:2F:(FotB_001C)
{
[Style right]
Oaklie! Are you alright?[BR]
[Wait][End]
}






#message:2F:(FotB_001D)
{
[Style right]
Hmm? Oh my, it's you two![BR]
[Wait][Next]
Thank you for saving me. That[BR]
chest is difficult to breathe in.[BR]
[Wait][End]
}






#message:2F:(FotB_001E)
{
[Style right]
What's going on around here?[BR]
Why is the forest in such[BR]
disarray?[BR]
[Wait][Next]
The old directions don't work[BR]
and there's boulders everywhere![BR]
We can't even make our way[BR]
back to the Manor![BR]
[Wait][End]
}






#message:2F:(FotB_001F)
{
[Style right]
Hmm...[BR]
[Wait][Next]
I've been in that chest[BR]
too long, I have no idea what[BR]
has happened today.[BR]
[Wait][Next]
I was on my way to clear out[BR]
some invasive nests when those[BR]
bullies ambushed me and[BR]
trapped me inside that chest.[BR]
[Wait][End]
}






#message:2F:(FotB_0020)
{
[Style right]
I see your words are true...[BR]
I feel uneasiness in the[BR]
forest tonight...[BR]
[Wait][End]
}






#message:2F:(FotB_0021)
{
[Style right]
Would you be able to guide us[BR]
through the forest? Surely you[BR]
know of some hidden detours[BR]
we can make use of.[BR]
[Wait][End]
}






#message:2F:(FotB_0022)
{
[Style right]
There are some tunnels beneath[BR]
this forest that have been[BR]
closed off for many years.[BR]
[Wait][Next]
I will open them for tonight only,[BR]
I must be careful to not expose[BR]
them for too long.[BR]
[Wait][End]
}






#message:2F:(FotB_0023)
{
[Style right]
Follow me to the clearing.[BR]
[Wait][End]
}






#message:2F:(FotB_0024)
{
[Style right]
Here we are.[BR]
[Wait][Next]
You can use this pipe to arrive[BR]
at the back entrance to these[BR]
woods and get home.[BR]
[Wait][Next]
Keep on your path and you[BR]
should arrive safely.[BR]
[Wait][End]
}






#message:2F:(FotB_0025)
{
[Style right]
Oh wonderful! Thank you Oaklie![BR]
[Wait][End]
}






#message:2F:(FotB_0026)
{
[Style right]
Come now Mario, a fancy feast[BR]
awaits you![BR]
[Wait][End]
}


#message:2F:(FotB_0027)
{
[Style Inspect]
There are noises coming from[BR]
the rock.[BR]
[Wait][Next]
It sounds like snoring.[BR]
[Wait][End]
}



#message:2F:(FotB_0028)
{
[Style right]
I hear talk of a dinner party,[BR]
were those Boos back there[BR]
on the guest list?[BR]
[Wait][End]
}


#message:2F:(FotB_0029)
{
[Style right]
Oh, not at all! We don’t know[BR]
where those bullies came from![BR]
[Wait][End]
}


#message:2F:(FotB_002A)
{
[Style right]
I expect my visitors to display[BR]
more class than that! I wouldn’t[BR]
invite such dirty ruffians to[BR]
such a fancy dinner![BR]
[Wait][End]
}


#message:2F:(FotB_002B)
{
[Style right]
Ah, is that right? It sounds like[BR]
quite a fun time every year...[BR]
[Wait][Next]
Companions are rare in the[BR]
forest, usually we’re the[BR]
dinner here...[BR]
[Wait][End]
}


#message:2F:(FotB_002C)
{
[Style right]
Oh! Pardon me![BR]
[Wait][Next]
You should move along before[BR]
the weather gets fierce, head[BR]
into that Pipe to reach the back[BR]
entrance of the forest.[BR]
[Wait][End]
}


